sudo: required
dist: trusty
language: node_js
node_js:
  - 12.4.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libsecret-1-dev
      - libstdc++6
      - gnome-keyring
      - python-gnomekeyring
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run ci
cache: npm