sudo: required
dist: trusty
language: node_js
node_js:
  - 10.2.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libsecret-1-dev
      - libstdc++6
      - gnome-keyring
      - python-gnomekeyring
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run ci
cache:
  directories:
    - $HOME/.electron
    - node_modules
