sudo: required
dist: trusty
language: node_js
node_js:
  - 7.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm run ci
cache:
  directories:
    - $HOME/.electron
    - node_modules
